image:
  registry: ghcr.io
  repository: mconfalonieri/external-dns-hetzner-webhook
  tag: latest
  pullPolicy: Always

provider: webhook

sources:
  - service

logLevel: debug

extraArgs:
  webhook-provider-url: http://localhost:8888

sidecars:
  - name: webhook
    image: ghcr.io/mconfalonieri/external-dns-hetzner-webhook:latest
    imagePullPolicy: Always
    ports:
      - containerPort: 8888
        name: http
    livenessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 10
      timeoutSeconds: 5
    env:
      - name: DRY_RUN
        value: "true"
      #      - name: DOMAIN_FILTER
      #        value: "test.com,test.de"
      #      - name: EXCLUDE_DOMAIN_FILTER
      #        value: "test.com,test.de"
      #      - name: REGEXP_DOMAIN_FILTER
      #        value: ""
      #      - name: REGEXP_DOMAIN_FILTER_EXCLUSION
      #        value: ""
      - name: SERVER_HOST
        value: "0.0.0.0"
      - name: HETZNER_API_KEY
        value: "put your api key here"
      - name: HETZNER_DEBUG
        value: "true"
